apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: drkiq
  name: drkiq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: drkiq
    spec:
      containers:
      - args:
        - bash
        - -c
        - rake db:reset && rake db:migrate && bundle exec unicorn -c config/unicorn.rb
        env:
        - name: CACHE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CACHE_URL
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_URL
        - name: JOB_WORKER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JOB_WORKER_URL
        - name: LISTEN_ON
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LISTEN_ON
        - name: SECRET_TOKEN
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SECRET_TOKEN
        - name: WORKER_PROCESSES
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: WORKER_PROCESSES
        image: mennatallahshaaban/drkiq:1.3
        name: drkiq
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
