version: '2'
services:
  postgres:
    image: postgres:9.4.5
    container_name: postgres
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.0.5
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - drkiq-redis:/var/lib/redis/data

  drkiq:
    image: mennatallahshaaban/drkiq:1.3
    container_name: drkiq
    links:
      - postgres
      - redis
    volumes:
      - /home/menna/workspace/ruby-rails-dockerization/drkiq:/drkiq
    ports:
      - '8000:8000'
    env_file:
      - /home/menna/workspace/ruby-rails-dockerization/drkiq/.drkiq.env

  sidekiq:
    image: mennatallahshaaban/drkiq:1.3
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - postgres
      - redis
    volumes:
      - /home/menna/workspace/ruby-rails-dockerization/drkiq:/drkiq
    env_file:
      - /home/menna/workspace/ruby-rails-dockerization/drkiq/.drkiq.env

volumes:
  drkiq-postgres:
  drkiq-redis:
